const string = {
  app_name: "iResident",
  login: "Inicio de sesion",
  signup: "Registrate",
  email: "Correo electrónico",
  password: "contraseña",
  welcome_to: "Bienvendid@! a",
  sign_in_to_continue: "Inicia sesión para continuar.",
  remember_password: "Recordar usuario.",
  get_into: "Get into",
  in_development: "In Development",
  i_forgot_password: "Olvide mi constraseña",
  complete_following_register: "Completa lo siguiente para \nregistrarte",
  name: "Nombre",
  first_name: "Primer nombre",
  last_name: "Apellido paterno",
  register: "Registrar",
  repeat_password: "Repetir contraseña",
  you_are_not_part_of_iresident: "Aún no eres parte de un grupo \niResident.",
  enter_the_code: "Ingresa el código de tu complejo",
  join_me: "Unirme",
  surveillance: "Vigilancias",
  regulation: "Reglamento",
  guests: "Invitados",
  mailbox: "Buzón",
  notification: "Notificaciones",
  addressheader1: "Frontemare",
  addressheader2: "Conjunto residencial",
};

export default string;
